install_data('indicator-sensors-16x16.png',
             rename: ['indicator-sensors.png'],
             install_dir: get_option('datadir') / 'icons/hicolor/16x16/apps' )
install_data('indicator-sensors-24x24.png',
             rename: ['indicator-sensors.png'],
             install_dir: get_option('datadir') / 'icons/hicolor/24x24/apps' )
install_data('indicator-sensors-32x32.png',
             rename: ['indicator-sensors.png'],
             install_dir: get_option('datadir') / 'icons/hicolor/32x32/apps' )
install_data('indicator-sensors-48x48.png',
             rename: ['indicator-sensors.png'],
             install_dir: get_option('datadir') / 'icons/hicolor/48x48/apps' )
install_data('indicator-sensors-256x256.png',
             rename: ['indicator-sensors.png'],
             install_dir: get_option('datadir') / 'icons/hicolor/256x256/apps' )

install_data('indicator-sensors-battery.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/devices')
install_data('indicator-sensors-case.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/devices')
install_data('indicator-sensors-chip.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/devices')
install_data('indicator-sensors-cpu.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/devices')
install_data('indicator-sensors-disk.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/devices')
install_data('indicator-sensors-fan.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/devices')
install_data('indicator-sensors-gpu.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/devices')
install_data('indicator-sensors-memory.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/devices')
install_data('indicator-sensors-no-icon.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/devices')

install_data('very-low-value-icon.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/status')
install_data('low-value-icon.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/status')
install_data('normal-value-icon.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/status')
install_data('high-value-icon.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/status')
install_data('very-high-value-icon.png',
             install_dir: get_option('datadir') / 'icons/hicolor/22x22/status')

install_data('indicator-sensors.svg',
             install_dir: get_option('datadir') / 'icons/hicolor/scalable/apps')
