name: indicator-sensors
version: git
summary: Provide hardware sensors readings in your desktop panel
description: |
 Application indicator to display and monitor the readings
 from various hardware sensors (temperature, fan speeds, voltages
 etc) in the desktop panel

base: core18
grade: stable
confinement: strict
icon: icons/hicolor/256x256/apps/indicator-sensors.png
license: GPL-3.0+

slots:
  # for GtkApplication registration
  indicator-sensors:
    interface: dbus
    bus: session
    name: com.github.alexmurray.IndicatorSensors

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804:gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes

environment:
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

apps:
  indicator-sensors:
    command: desktop-launch indicator-sensors
    plugs:
      - x11
      - unity7
      - desktop
      - wayland
      - gsettings
      - udisks2
      - hardware-observe
    desktop: usr/share/applications/indicator-sensors.desktop
    # snapcraft doesn't know about the autostart field
    passthrough:
      autostart: indicator-sensors.desktop

parts:
  indicator-sensors:
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    plugin: autotools
    configflags: [--prefix=/snap/indicator-sensors/current/usr]
    organize:
      snap/indicator-sensors/current/usr: usr
    build-packages:
      - intltool
      - gnome-common
      - libglib2.0-dev
      - libgdk-pixbuf2.0-0
      - libgtk-3-dev
      - libpeas-dev
      - libnotify-dev
      - libappindicator3-dev
      - libsensors4-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - libudisks2-dev
      - try: [ libxnvctrl-dev ]
    override-prime: |
      set -eu
      snapcraftctl prime
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' usr/share/applications/indicator-sensors.desktop

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  libraries:
    plugin: nil
    stage-packages:
       - libsensors4
       - libappindicator3-1
       - libudisks2-0
       - libnotify4
       - libpeas-1.0-0
       - try: [ libxnvctrl0 ]
    prime:
      # include only what we need which is not in the desktop-gnome-platform to
      # keep the snap size as small as possible
      - etc/sensors3.conf
      - etc/sensors.d/*
      - usr/lib/*/libappindicator3.so.*
      - usr/lib/*/libdbusmenu-glib.so.*
      - usr/lib/*/libdbusmenu-gtk3.so.*
      - usr/lib/*/libindicator3.so.*
      - usr/lib/*/libsensors.so.*
      - usr/lib/*/libudisks2.so.*
      - usr/lib/*/libXNVCtrl.so.*
