name: indicator-sensors
version: git
summary: Provide hardware sensors readings in your desktop panel
description: |
 Application indicator to display and monitor the readings
 from various hardware sensors (temperature, fan speeds, voltages
 etc) in the desktop panel

base: core22
grade: stable
confinement: strict
icon: icons/hicolor/256x256/apps/indicator-sensors.png
license: GPL-3.0+

slots:
  # for GtkApplication registration
  indicator-sensors:
    interface: dbus
    bus: session
    name: com.github.alexmurray.IndicatorSensors

environment:
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

apps:
  indicator-sensors:
    command: usr/bin/indicator-sensors
    extensions: [gnome]
    plugs:
      - unity7
      - udisks2
      - hardware-observe
    desktop: usr/share/applications/indicator-sensors.desktop
    autostart: indicator-sensors.desktop

parts:
  indicator-sensors:
    source: .
    plugin: autotools
    autotools-configure-parameters: [--prefix=/snap/indicator-sensors/current/usr]
    organize:
      snap/indicator-sensors/current/usr: usr
    build-packages:
      - intltool
      - gnome-common
      - libglib2.0-dev
      - libgdk-pixbuf2.0-0
      - libgtk-3-dev
      - libpeas-dev
      - libnotify-dev
      - libayatana-appindicator3-dev
      - libsensors-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - libudisks2-dev
      - libxnvctrl-dev
    override-prime: |
      set -eu
      snapcraftctl prime
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' usr/share/applications/indicator-sensors.desktop

  libraries:
    plugin: nil
    stage-packages:
       - libsensors5
       - libayatana-appindicator3-1
       - libayatana-indicator3-7
       - libayatana-ido3-0.4-0
       - libudisks2-0
       - libnotify4
       - libpeas-1.0-0
       - libgtk3-nocsd0
       - libxnvctrl0
    prime:
      # include only what we need which is not in the desktop-gnome-platform to
      # keep the snap size as small as possible
      - etc/sensors3.conf
      - etc/sensors.d/*
      - usr/lib/*/libayatana-appindicator3.so.*
      - usr/lib/*/libayatana-indicator3.so.*
      - usr/lib/*/libayatana-ido3-0.4.so.*
      - usr/lib/*/libdbusmenu-glib.so.*
      - usr/lib/*/libdbusmenu-gtk3.so.*
      - usr/lib/*/libindicator3.so.*
      - usr/lib/*/libsensors.so.*
      - usr/lib/*/libudisks2.so.*
      - usr/lib/*/libXNVCtrl.so.*
      - usr/lib/*/libgtk3-nocsd.so.*
