name: indicator-sensors
version: '0.8+git'
summary: Provide hardware sensors readings in your desktop panel
description: |
 Application indicator to display and monitor the readings
 from various hardware sensors (temperature, fan speeds, voltages
 etc) in the desktop panel

grade: devel
confinement: strict
icon: pixmaps/indicator-sensors.png

slots:
  # for GtkApplication registration
  indicator-sensors:
    interface: dbus
    bus: session
    name: com.github.alexmurray.IndicatorSensors

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604:gnome-3-26-1604

apps:
  indicator-sensors:
    command: desktop-launch indicator-sensors
    plugs:
      - x11
      - unity7
      - desktop
      - wayland
      - gsettings
      - pulseaudio
      - home
      - udisks2
      - hardware-observe
    desktop: usr/share/applications/indicator-sensors.desktop

parts:
  indicator-sensors:
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    plugin: autotools
    configflags: [--prefix=/snap/indicator-sensors/current/usr]
    organize:
      snap/indicator-sensors/current/usr: usr
    build-attributes: [no-system-libraries]
    build-packages:
      - intltool
      - gnome-common
      - gnome-doc-utils
      - libglib2.0-dev
      - libgdk-pixbuf2.0-0
      - libgtk-3-dev
      - libpeas-dev
      - libnotify-dev
      - libappindicator3-dev
      - libsensors4-dev
      - gobject-introspection
      - libgirepository1.0-dev
      # not available on all arch
      - try: [nvidia-settings]
      - libudisks2-dev
    stage-packages:
      - libappindicator3-1
      - libudisks2-0
